[package]
name = "Bartend"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
iced = { version = "0.14.0", features = ["tokio", "wgpu", "debug"] }
iced_core = "0.14.0"
rfd = "0.17.2"
rusqlite = { version = "0.38.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[dev-dependencies]
tempfile = "3.24.0"
